#!/bin/sh
#
# An example hook script for the "post-receive" event.

APP="Gift - API"
APP_ROOT=/srv/www/gift/api


echo "*************"
echo "Deploying $APP"
echo "*************"

cd $APP_ROOT || echo "Missing app root."

unset GIT_DIR
git pull origin master


echo "**************"
echo "Deploy end."
echo "**************"